# Generated by Django 2.1.3 on 2018-11-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(choices=[('Iron Man', 'Iron Man'), ('Captain America', 'Captain America'), ('Thor', 'Thor')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(default='Image', upload_to='post/')),
                ('image_caption', models.CharField(max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=False, to='marvel.Category')),
            ],
        ),
    ]
